// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP0LhYL-Dlz501CpynsjVwqL3pSWX8rHE',
    appId: '1:358465763062:web:90dc93feab0a39beb55ed7',
    messagingSenderId: '358465763062',
    projectId: 'gorun-a9277',
    authDomain: 'gorun-a9277.firebaseapp.com',
    storageBucket: 'gorun-a9277.firebasestorage.app',
    measurementId: 'G-Q3T1425J52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbQfWUMHnOnEkJpm15PyE0iQp5tGXa6M',
    appId: '1:358465763062:android:59fb556378330dabb55ed7',
    messagingSenderId: '358465763062',
    projectId: 'gorun-a9277',
    storageBucket: 'gorun-a9277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKaaO8wHzJs_4ejhZEcN3gT5xWsSuHkc',
    appId: '1:358465763062:ios:c95be4a01f3715feb55ed7',
    messagingSenderId: '358465763062',
    projectId: 'gorun-a9277',
    storageBucket: 'gorun-a9277.firebasestorage.app',
    iosClientId: '358465763062-5fikvcd21frkg19u6rd8lsa68gd2gpbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendGorun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP0LhYL-Dlz501CpynsjVwqL3pSWX8rHE',
    appId: '1:358465763062:web:419affc29b2efac4b55ed7',
    messagingSenderId: '358465763062',
    projectId: 'gorun-a9277',
    authDomain: 'gorun-a9277.firebaseapp.com',
    storageBucket: 'gorun-a9277.firebasestorage.app',
    measurementId: 'G-K8RYMY7LMT',
  );

}